In [2]:
# from transformers import AutoTokenizer, AutoModelForCausalLM

# model = AutoModelForCausalLM.from_pretrained("amir-ma71/Dorna-Llama3-8B-Instruct-AWQ")

RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 234881024 bytes.

In [19]:
# tokenizer = AutoTokenizer.from_pretrained("amir-ma71/Dorna-Llama3-8B-Instruct-AWQ")

In [180]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [10]:
model = AutoModelForCausalLM.from_pretrained(
    "amir-ma71/Dorna-Llama3-8B-Instruct-AWQ",
    torch_dtype=torch.float16,
    device_map="cuda",
)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [3]:
import os
os.environ['HF_TOKEN']='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'

token2 = "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"

In [5]:
# from huggingface_hub import notebook_login
# notebook_login()

In [11]:
tokenizer = AutoTokenizer.from_pretrained(
                                          "PartAI/Dorna-Llama3-8B-Instruct",
                                        #   "amir-ma71/Dorna-Llama3-8B-Instruct-AWQ",
                                          token='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'
                                          )

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


### For chat


In [189]:
messages = [
    {"role": "system",
    #  "content": "You are a helpful Persian assistant. Please answer questions in the asked language.",
    #  "content": "You are a helpful Persian assistant. Please answer questions in the asked language."
     },
    {"role": "user", "content": "hello"},
]

input_ids = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=False,
    return_tensors="pt",
    # tokenize=False
).to(
    # model.device
    "cuda"
    )

print(tokenizer.decode(input_ids[0]))

<|start_header_id|>user<|end_header_id|>

hello<|eot_id|><|start_header_id|>assistant<|end_header_id|>




In [193]:
input_ids = tokenizer('hello',
                      return_tensors="pt")['input_ids'].to(
    # model.device
    "cuda"
    )
input_ids

tensor([[15339]], device='cuda:0')

In [197]:
tokenizer.vocab_size

128000

In [196]:
terminators = [
    tokenizer.eos_token_id,
    tokenizer.convert_tokens_to_ids("<|eot_id|>")
]

outputs = model.generate(
    input_ids,
    max_new_tokens=256,
    eos_token_id=terminators,
    do_sample=True,
    temperature=0.6,
    top_p=0.9,
)

response = outputs[0][input_ids.shape[-1]:]
print(tokenizer.decode(response, skip_special_tokens=True))

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128009 for open-end generation.


 noreferrer</p>
<p><input type="number" id="input" value="0" min="0" step="1" oninput="this.value = Math.floor(this.value)"></p>
<p id="result">0</p>
```
```javascript
function updateResult() {
  let inputVal = parseInt(document.getElementById("input").value);
  document.getElementById("result").innerHTML = inputVal;
}

document.getElementById("input").addEventListener("input", updateResult);
```
In this code, we first create an input field with a `number` type, and set its initial value to 0. We also set the `min` and `step` attributes to ensure that only integer values are accepted.

Next, we create a `p` element to display the result, and set its initial value to 0.

We define a JavaScript function `updateResult()` that updates the result by getting the current value of the input field using `document.getElementById("input").value`, parsing it to an integer using `parseInt()`, and setting the inner HTML of the result element to this value.

Finally, we add an event listener to the i

### For Embedding generation


In [320]:
texts = [
    "i feel very good",
    "i feel sad and bad"
]

# texts = ["man woman"]

encoded_texts = tokenizer(
    texts,
    return_tensors='pt',
    padding=True,
    truncation=True
).to("cuda")

input_ids = encoded_texts['input_ids']

with torch.no_grad():
    outputs = model(input_ids,
                    return_dict=True,
                    output_hidden_states=True,
                    # output_attentions=True
                    # last_hidden_state=True,
                    # pooler_output=True
                    )

last_hidden_layer = outputs['hidden_states'][-1]

# for item in logits:
#     print(item)
#     print(tokenizer.decode(item, end="\n"))

a = np.mean(last_hidden_layer[0].cpu().detach().numpy().astype('float64'), axis=0).reshape(1, -1) 
b = np.mean(last_hidden_layer[1].cpu().detach().numpy().astype('float64'), axis=0).reshape(1, -1)

cosine_similarity(a, b)

array([[0.71495467]])

In [319]:
a[0]

array([-2.19550781,  1.49746094,  2.08046875, ...,  0.74851074,
        0.89470215,  1.55429687])

In [314]:
b

array([[-1.82060547,  1.19541016,  1.29023438, ..., -0.34819336,
         1.23164063,  1.75766602]])

In [297]:
outputs['hidden_states'][-1]

tensor([[[-1.8340, -0.9365,  0.7080,  ..., -0.1449,  1.1914, -0.2466],
         [-2.3457,  1.6279,  2.6113,  ...,  1.9297,  1.5293,  3.3535],
         [-2.0176,  1.9326,  2.4785,  ...,  0.4248,  0.5659,  1.4570],
         [-1.6260,  1.3691,  1.1240,  ...,  0.2605,  1.3945,  0.8989],
         [-3.1543,  3.4941,  3.4805,  ...,  1.2725, -0.2076,  2.3086]],

        [[-3.0430,  2.9609,  1.5518,  ...,  1.5996, -1.5635,  4.0820],
         [-0.6597,  1.2598,  0.1606,  ..., -2.2637,  1.3750, -0.0828],
         [-1.8818,  2.3281,  1.7383,  ..., -0.2834,  2.7363,  2.3262],
         [-1.7354, -0.2444,  2.6699,  ...,  0.6616,  1.8857,  1.1963],
         [-1.7832, -0.3274,  0.3306,  ..., -1.4551,  1.7246,  1.2666]]],
       device='cuda:0', dtype=torch.float16)

In [305]:
np.mean(last_hidden_layer[0].cpu().detach().numpy().astype('float64'), axis=0)

array([-2.19550781,  1.49746094,  2.08046875, ...,  0.74851074,
        0.89470215,  1.55429687])

In [324]:
from transformers import pipeline

pipe = pipeline(
    "feature-extraction", 
    model=model, 
    torch_dtype=torch.float32, 
    device_map="cuda",
    tokenizer=tokenizer
)

embeds = pipe(
    [
    "i feel very good",
    "i feel sad and bad"
    ],
    tokenizer=tokenizer,
    eos_token_id=tokenizer.eos_token_id,
)

In [327]:
cosine_similarity(embeds[0], embeds[1])

ValueError: Found array with dim 3. check_pairwise_arrays expected <= 2.

In [339]:
torch.as_tensor(embeds)

ValueError: expected sequence of length 4 at dim 2 (got 5)